### ISSUE TITLE
Add "only for JAVA", on the landing page.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#310]
Somehow users don't think it is obvious that this is only for java at the moment and they try random things and go away. 

@hashd

**Comment by hashd** [comment]
@uidev547 can you add it as a note right at the bottom of the landing web page

**Comment by uidev547** [comment]
I guess this is fixed after adding "Search as **java** terms / Code"

**Comment by ScrapCodes** [comment]
Ahh Yes, It is not fixed. That was my quick and temporary suggestion.
Because, I did not like the right corner location either.

"I do not want to say we are for JAVA forever nor I want to hide in corner
that we are for java currently"

Can you make this evident ?

Prashant Sharma

**Comment by hashd** [comment]
@uidev547 Prashant has a valid point, current description might make a wrong impression on the users mind.

A good approach can be to have a asterisk on **Search* Code\*

and in the footer address it as `*Currently we only support Java. Support for other languages will be released soon.`
